### ISSUE TITLE
Lage randomJokeMetode

### ISSUE THREAD

**Issue by Nosp1** [brisdalen/is-308-2020#9]
lage en metode som tar imot en request på  "/joke/random"

**Comment by brisdalen** [comment]
@heiaviking @hennibryne Dere lyst til å prøve på denne? 😄

**Comment by heiaviking** [comment]
Ja gjerne, prøve med Henriette på mandag eller sette ned med imorgen🔥🔥

Sendt fra min iPhone

5. sep. 2020 kl. 21:11 skrev Bjørnar <notifications@github.com>:

﻿

@heiaviking<https://github.com/heiaviking> @hennibryne<https://github.com/hennibryne> Dere lyst til å prøve på denne? 😄
